- name: Linux target
  hosts: all
  become: true
  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        update_cache: yes
        name: python3
        state: present
    #- name: Git checkout
    #  ansible.builtin.git:
    #    repo: 'https://github.com/mazen160/struts-pwn_CVE-2017-9805.git'
    #    dest: /opt/struts-pwn
    - name: Extract Exploit Script
      ansible.builtin.unarchive:
        src: ./data/struts-pwn.tar.gz
        dest: /opt