---
- name: Install and Run Exploit for Spring Cloud Config Server Directory Traversal Vulnerability (CVE-2020-5405)
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

